name: Makefile CI - CPops

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: init dependencies
      run: make init

    - name: execute app
      run: make execute
    
    - name: Stop app
      run: make finish
